### ISSUE TITLE
Request for ARM64 Support for Docker Images

### ISSUE THREAD

**Issue by RayShaw97** [wolfderechter/taiko-node-dashboard#18]
Hello,

I'm trying to run docker containers on OCI's arm64 VM but found that the existing image doesn't support that platform, can you add support for the ARM64 platform?
![image](https://github.com/dojonode/taiko-node-dashboard/assets/152388631/c73794da-46dd-4fd3-8279-97a7a7afc9f5)

### Suggested Solution

I'm not familiar with github flow, but GPT-4 suggests adding "linux/arm64" to "platforms" in the "Build and push latest" step.

Thank you for considering this enhancement.

**Comment by wolfderechter** [comment]
Thanks for noting the issue, should be fixed now. Can you try and let me know? Thanks

**Comment by RayShaw97** [comment]
It ran successfully. But I ran into another problem.

I have all containers running under the same docker compose project, but dashboard is not able to establish a connection through the service name, even though I can ping the simple-taiko-node-taiko-node-systeminfo-1 container in the simple-taiko-node-prometheus-1
![image](https://github.com/dojonode/taiko-node-dashboard/assets/152388631/d85b02da-f2f1-4adb-9f90-8ab4c6326498)
![image](https://github.com/dojonode/taiko-node-dashboard/assets/152388631/329ac6e2-63d7-4f07-b3a6-0ec008ceab4e)
![image](https://github.com/dojonode/taiko-node-dashboard/assets/152388631/c9024c3c-7960-4f76-a5b5-0b122788abd2)

**Comment by wolfderechter** [comment]
> It ran successfully. But I ran into another problem.
> 
> I have all containers running under the same docker compose project, but dashboard is not able to establish a connection through the service name, even though I can ping the simple-taiko-node-taiko-node-systeminfo-1 container in the simple-taiko-node-prometheus-1 ![image](https://private-user-images.githubusercontent.com/152388631/327657996-d85b02da-f2f1-4adb-9f90-8ab4c6326498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI0MDEsIm5iZiI6MTcxNDcyMjEwMSwicGF0aCI6Ii8xNTIzODg2MzEvMzI3NjU3OTk2LWQ4NWIwMmRhLWYyZjEtNGFkYi05ZjkwLThhYjRjNjMyNjQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWMzMDdhYTliNWFmYzFlNGRjOTU1MmE2NTc5MzU2ODcxZjdjY2Q5MjNkZjRlMmEyYTcwMDkxNmFlYWZjZDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iotaYwcHOtR3QM8iPmQudI22vCCUz6hLLlRvsN_gGLU) ![image](https://private-user-images.githubusercontent.com/152388631/327658698-329ac6e2-63d7-4f07-b3a6-0ec008ceab4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI0MDEsIm5iZiI6MTcxNDcyMjEwMSwicGF0aCI6Ii8xNTIzODg2MzEvMzI3NjU4Njk4LTMyOWFjNmUyLTYzZDctNGYwNy1iM2E2LTBlYzAwOGNlYWI0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDkzNjdjMDkwZmY4M2Y4ZjlmZTM1YzRkMTIzNGM5Mjc5NjQzNGJmYzU3N2ZlYjQ5MWI5NGRlZGM4NmFkZWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x1WZ_k-37_pJkREkLi7mDY8U7qag7Uo_mpGrf1hSRxQ) ![image](https://private-user-images.githubusercontent.com/152388631/327658096-c9024c3c-7960-4f76-a5b5-0b122788abd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI0MDEsIm5iZiI6MTcxNDcyMjEwMSwicGF0aCI6Ii8xNTIzODg2MzEvMzI3NjU4MDk2LWM5MDI0YzNjLTc5NjAtNGY3Ni1hNWI1LTBiMTIyNzg4YWJkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGNjNmMzZDgyMjAxMTIxZjI0OWQzZDE5NGI4ZmRjYzU1MGVkYTkzNGVkZDMxODE5ODM1ZWEyODQ3NTM0Y2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._AG0dyt50iifpM0effjI3twH-gTlaRDoNzqnk_4ckKE)

I believe the docker containers name aren't recognized unfortunately, you need to use an IP address. This can be either the internal IP (192.168.x.x) or the public IP address

**Comment by RayShaw97** [comment]
According to the grafana in the official docker-compose.yml, at least Prometheus is accessible via the service name. I think the URL in the image below should also work on the dashboard too, typically.
Is there any way to make the dashboard container output debug level logs? A more detailed log might help with that!
![image](https://github.com/dojonode/taiko-node-dashboard/assets/152388631/a08c6993-5bbf-4c84-8806-b7cf3ff03d67)

**Comment by RayShaw97** [comment]
> > It ran successfully. But I ran into another problem.
> > I have all containers running under the same docker compose project, but dashboard is not able to establish a connection through the service name, even though I can ping the simple-taiko-node-taiko-node-systeminfo-1 container in the simple-taiko-node-prometheus-1 ![image](https://private-user-images.githubusercontent.com/152388631/327657996-d85b02da-f2f1-4adb-9f90-8ab4c6326498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI0MDEsIm5iZiI6MTcxNDcyMjEwMSwicGF0aCI6Ii8xNTIzODg2MzEvMzI3NjU3OTk2LWQ4NWIwMmRhLWYyZjEtNGFkYi05ZjkwLThhYjRjNjMyNjQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWMzMDdhYTliNWFmYzFlNGRjOTU1MmE2NTc5MzU2ODcxZjdjY2Q5MjNkZjRlMmEyYTcwMDkxNmFlYWZjZDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iotaYwcHOtR3QM8iPmQudI22vCCUz6hLLlRvsN_gGLU) ![image](https://private-user-images.githubusercontent.com/152388631/327658698-329ac6e2-63d7-4f07-b3a6-0ec008ceab4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI0MDEsIm5iZiI6MTcxNDcyMjEwMSwicGF0aCI6Ii8xNTIzODg2MzEvMzI3NjU4Njk4LTMyOWFjNmUyLTYzZDctNGYwNy1iM2E2LTBlYzAwOGNlYWI0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDkzNjdjMDkwZmY4M2Y4ZjlmZTM1YzRkMTIzNGM5Mjc5NjQzNGJmYzU3N2ZlYjQ5MWI5NGRlZGM4NmFkZWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x1WZ_k-37_pJkREkLi7mDY8U7qag7Uo_mpGrf1hSRxQ) ![image](https://private-user-images.githubusercontent.com/152388631/327658096-c9024c3c-7960-4f76-a5b5-0b122788abd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI0MDEsIm5iZiI6MTcxNDcyMjEwMSwicGF0aCI6Ii8xNTIzODg2MzEvMzI3NjU4MDk2LWM5MDI0YzNjLTc5NjAtNGY3Ni1hNWI1LTBiMTIyNzg4YWJkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGNjNmMzZDgyMjAxMTIxZjI0OWQzZDE5NGI4ZmRjYzU1MGVkYTkzNGVkZDMxODE5ODM1ZWEyODQ3NTM0Y2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._AG0dyt50iifpM0effjI3twH-gTlaRDoNzqnk_4ckKE)
> 
> I believe the docker containers name aren't recognized unfortunately, you need to use an IP address. This can be either the internal IP (192.168.x.x) or the public IP address

It turns out that the container actually only provides a web page to run in my browser, so no wonder my configuration didn't take effect, sorry for not understanding you! 

But for those who run taiko node on the cloud, it's dangerous to expose so many APIs to the internet just to use the dashboard.

I think it would be better to forward these APIs through the nginx in container.

**Comment by wolfderechter** [comment]
> It turns out that the container actually only provides a web page to run in my browser, so no wonder my configuration didn't take effect, sorry for not understanding you!
> 
> But for those who run taiko node on the cloud, it's dangerous to expose so many APIs to the internet just to use the dashboard.
> 
> I think it would be better to forward these APIs through the nginx in container.

Yes that's how it works and indeed it would not be wise to just expose every port. That's why I recommend using tailscale or other VPN's which let you easily access ports on remote computers
