### ISSUE TITLE
Make the connection to the metrics internal

### ISSUE THREAD

**Issue by maxysoft** [wolfderechter/taiko-node-dashboard#19]
Hello,
is it possbile to make the dashboard connect to metrics only internally without the need to specify manually the metrics urls and avoid exposing these services publically? Thanks.

**Comment by wolfderechter** [comment]
Good question, not at the moment no. I would advise to do as I do and use tailscale. This way you can setup the host of the node with a name like 'eth-pc' and simply use `http://eth-pc:8548` from anywhere without exposing. There are also other alternative VPN's but this has been the easiest solution for me

**Comment by maxysoft** [comment]
Do you think can be implemented in the future? Using a vpn for private use can work but that means I cannot expose publically the dashboard, if there is the intention.

Something like: if you set manually the connections in a env or config file, the 📡 button is hidden/disabled.

**Comment by wolfderechter** [comment]
No not really, because the dashboard is client-side so all the requests come from the browser you are viewing the dashboard on.
